### ISSUE TITLE
Publish container images

### ISSUE THREAD

**Issue by svenstaro** [harlanc/xiu#100]
I really like xiu but currently deploying it is a bit tedious because I first need to compile it on my server and then start it. I think it might be more convenient if you used either DockerHub or the GitHub Container Registry to publish pre-built images (with the WebRTC web files in the right location for the binary already).

This could also solve #80 if you published multi-arch packages. You can copy parts of the process from [miniserve](https://github.com/svenstaro/miniserve/blob/master/.github/workflows/build-release.yml) if you like.

**Comment by harlancc** [comment]
@rsubr  Thanks for your new idea to build xiu,  I run the script on my M1 Mac book,  after the compilation process is completed, a "xiu" binary will be generated on macOS, but this binary can only be run inside the docker image where xiu was compiled due to system differences, the system of docker is :

    Linux beb91e124e02 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 GNU/Linux

So this script will pull a corresponding Linux version for the CPU architecture of your physical machine for compilation., 

<img width="368" alt="image" src="https://github.com/harlanc/xiu/assets/90186099/7bc4cee5-a85b-412c-8a6f-8b64b4174538">


right？I will consider whether to add it to the repository, thank you. 😊

**Comment by harlanc** [comment]
@rsubr  Thanks for your new idea to build xiu,  I run the script on my M1 Mac book,  after the compilation process is completed, a "xiu" binary is generated on macOS, but this binary can only be run inside the docker image where xiu was compiled due to system differences, the system of docker is :

    Linux beb91e124e02 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 GNU/Linux

So this script will pull a corresponding Linux version for the CPU architecture of your physical machine for compilation., 

<img width="368" alt="image" src="https://github.com/harlanc/xiu/assets/90186099/7bc4cee5-a85b-412c-8a6f-8b64b4174538">


right？I will consider whether to add it to the repository, thank you. 😊

**Comment by harlanc** [comment]
@svenstaro 
Based on your GitHub Action workflow, pre-builds for some CPU architectures have been generated successfully, but the Docker image publishing failed which will be fixed in the next release. Thank you.

**Comment by svenstaro** [comment]
Great to hear!

**Comment by harlanc** [comment]
@svenstaro  A question about podman push in github action, where's the value of the environment variable "needs.publish.outputs.version" read from? I can retrieve the value during testing, but I don't know why I can't get it in the official release.

**Comment by svenstaro** [comment]
It's the output of a step of another job, see here: https://github.com/svenstaro/miniserve/blob/b78c59ead7184cbcc937153f36a5e6420e49b8d2/.github/workflows/build-release.yml#L10. This refers to this: https://github.com/svenstaro/miniserve/blob/b78c59ead7184cbcc937153f36a5e6420e49b8d2/.github/workflows/build-release.yml#L103

**Comment by murlakatamenka** [comment]
Since we talk about packaging and distribution here...

@svenstaro do you plan do add xiu to Arch repos or is it safe to make an AUR package?

I've been aware of it for a few years and using it from time to time, but didn't push to AUR for others.

**Comment by harlanc** [comment]
Install xiu [doc](https://www.rustxiu.com/v0.12.4/docs/getting-started/setup/)

**Comment by svenstaro** [comment]
> Since we talk about packaging and distribution here...
> 
> @svenstaro do you plan do add xiu to Arch repos or is it safe to make an AUR package?
> 
> I've been aware of it for a few years and using it from time to time, but didn't push to AUR for others.

I might push it to repos later on. Let's have it in AUR for now.

**Comment by murlakatamenka** [comment]
> I might push it to repos later on. Let's have it in AUR for now.

okay, boss

https://aur.archlinux.org/packages/xiu
